categories:
  friends-nuts:
    bergfreunde:
      - https://www.bergfreunde.eu/camming-devices-friends/
      - https://www.bergfreunde.eu/nuts/
    mountex: https://mountex.hu/sziklamaszas-hegymaszas?v=115
    4camping: https://www.4camping.hu/c/hegymaszo-felszerelesek/friendek-es-ekek/
  slings:
    bergfreunde: https://www.bergfreunde.eu/slings-cord/
    mountex: https://mountex.hu/sziklamaszas-hegymaszas?v=110
    4camping: https://www.4camping.hu/c/hegymaszo-felszerelesek/hurkok-hevederek/
  ropes:
    bergfreunde: https://www.bergfreunde.eu/climbing-ropes/
    mountex: https://mountex.hu/sziklamaszas-hegymaszas?v=109
    4camping: https://www.4camping.hu/c/maszokoetelek/
  carabiners-quickdraws:
    bergfreunde: https://www.bergfreunde.eu/carabiners-quickdraws/
    mountex: https://mountex.hu/sziklamaszas-hegymaszas?v=107
    4camping: https://www.4camping.hu/c/hegymaszo-felszerelesek/karabinerek-expresszek/